### ISSUE TITLE
Assistance Required: Running Brain Extraction Tool for CT Head Images

### ISSUE THREAD

**Issue by anantpal07** [aqqush/CT_BET#12]
Dear aqqush,

I hope this email finds you well. My name is Anant Paliwal, and I am reaching out to seek your assistance regarding the implementation of your open-source tool for extracting brain CT images. I am currently facing some challenges while trying to run the code, specifically related to the model_CT_SS.py file.

Here is a summary of the issue:

*Error Description:*
root@e2e-101-176:~/CT_BET# python3 unet_CT_SS.py
unet_CT_SS.py
2024-01-11 03:17:53.828717: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-11 03:17:53.831627: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-11 03:17:53.876731: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-11 03:17:53.876790: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-11 03:17:53.878205: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-11 03:17:53.885791: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-11 03:17:53.886073: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-11 03:17:54.796159: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/root/CT_BET/unet_CT_SS.py", line 26, in <module>
    from model_CT_SS import Unet_CT_SS as genUnet
  File "/root/CT_BET/model_CT_SS.py", line 11, in <module>
    from keras.layers.core import Lambda
ModuleNotFoundError: No module named 'keras.layers.core'

*Request for Assistance:*
I have followed the instructions in the README file carefully, but I am experiencing difficulties running the python file unet_CT_SS.py. and the model_CT_SS.py needs changes as suggested by Chatgpt. I would greatly appreciate your guidance on resolving this issue. 

*Contact Information:*
If possible, could we schedule a brief call or exchange emails to address this concern more effectively? My contact information is as follows:
- Email: paliwalanant07@gmail.com
- Phone: +91-7745878018

*Additional Information:*
Chatgpt suggested to update the import statement from from keras.layers.core import Lambda to from tensorflow.keras.layers import Lambda but when I apply  these changes another error comes which is related to the import statement for multi_gpu_model and followed by many errors so on.

I understand that you may have a busy schedule, and I truly appreciate your time and support. Thank you for providing this valuable tool to the community, and I look forward to your assistance.

Best regards,

Anant Paliwal

**Comment by laurentletg** [comment]
Hello, I don't know if this can be useful but maybe try to set up an environement with these package versions : 

```txt
Keras==2.2.4
Keras_Applications==1.0.8
nibabel==2.0.0
numpy==1.21.6
protobuf==3.20.*
scikit_learn==1.0.2
scipy==1.7.3
SimpleITK==2.2.1
tensorflow==1.14.0
```
