### ISSUE TITLE
Image not 512x512

### ISSUE THREAD

**Issue by muschellij2** [aqqush/CT_BET#2]
If the image is not 512x512 which is the case because gantry tilt has been corrected from @rordenlab `dcm2niix` software, you get an error.  

```
2018-12-21 16:56:43.668278: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/johnmuschelli/Dropbox/Packages/CT_BET/image_data
('case: ', '03_BRAIN_1.nii.gz')
Traceback (most recent call last):
  File "unet_CT_SS_JM3.py", line 118, in <module>
    unetSS.Predict(weightFile)
  File "/Users/johnmuschelli/Dropbox/Packages/CT_BET/model_CT_SS.py", line 556, in Predict
    predImage = model.predict(testImages, batch_size=8, verbose=1)       
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1817, in predict
    check_batch_axis=False)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking : expected input_1 to have shape (512, 512, 1) but got array with shape (512, 551, 1)
```
For example, see the slightly padded image from your example and see if it works
[ct_20130524_1011_101232_j40s2_padded.nii.gz](https://github.com/aqqush/CT_BET/files/2704391/ct_20130524_1011_101232_j40s2_padded.nii.gz)

**Comment by muschellij2** [comment]
Just adding the padded mask for good measure.
[ct_20130524_1011_101232_j40s2_mask_padded.nii.gz](https://github.com/aqqush/CT_BET/files/2704396/ct_20130524_1011_101232_j40s2_mask_padded.nii.gz)

**Comment by aqqush** [comment]
Yes, input shape of images must be 512x512. You should pad zeros or resize it to that.
