### ISSUE TITLE
Issue with 3D Seg

### ISSUE THREAD

**Issue by muschellij2** [aqqush/CT_BET#7]
https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L211
I think it shoudl mirror https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L191

**Comment by aqqush** [comment]
Thanks John for pointing out this. It is fixed.
Z

**Comment by muschellij2** [comment]
Should https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L591 really need labels at all?  It seems anything with labels should be removed up until https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L601 (as long as you're not computing metrics)

Should https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L588 be loadTestData like https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L550?

**Comment by aqqush** [comment]
That part is not well organized but I made some changes for you. Hope it helps! Please let me know if you need any more help with running 3D model.

**Comment by muschellij2** [comment]
```
Traceback (most recent call last):
  File "unet_CT_SS.py", line 120, in <module>
    unetSS.Predict3D(weightFile)
  File "/Users/johnmuschelli/Dropbox/Packages/CT_BET/model_CT_SS.py", line 606, in Predict3D
    [numImgs,img_rows,img_cols,img_dep,ch] = testImages.shape
ValueError: not enough values to unpack (expected 5, got 3)
```
I think from https://github.com/aqqush/CT_BET/blob/master/model_CT_SS.py#L607

**Comment by aqqush** [comment]
Thanks. Move the line up.

**Comment by muschellij2** [comment]
Move it up?
